# ast-grep configuration file
ruleDirs:
  - ./sg_rules

# language specific configurations
languages:
  - id: python
    config: ./sg_rules/python.yml
  - id: typescript
    config: ./sg_rules/typescript.yml
  - id: javascript
    config: ./sg_rules/javascript.yml